### ISSUE TITLE
Missing gameType field

### ISSUE THREAD

**Issue by Zomis** [Zomis/Games#135]
When finishing a game, the game can't be saved in statistics because of this:

```
java.lang.IllegalStateException: Missing gameType field for game game:d7855a4d-a6d1-402e-9b5e-5ad07be56e2e
	at net.zomis.games.server2.db.SuperTable.getGameSummary(SuperTable.kt:323)
	at net.zomis.games.server2.db.aurora.StatsDB$saveNewlyFinishedInStats$2.invoke(StatsDB.kt:90)
	at net.zomis.games.server2.db.aurora.StatsDB$saveNewlyFinishedInStats$2.invoke(StatsDB.kt:21)
```

**Comment by Zomis** [comment]
This was due to some old games missing the gameType field. It has been resolved.
